### ISSUE TITLE
Conflicts with pods with require Run Script build phases.

### ISSUE THREAD

**Issue by brianpartridge** [Yelp/cocoapods-readonly#2]
I'm using this with the [CrashlyticsFramework](https://github.com/bpoplauschi/CrashlyticsFramework) pod and ran into trouble because I the `run` script had it's permissions changed and then it couldn't run at build time.

I think the right solution for this is to not set blanket 444 permissions, but to only remove write access if write access is set.  Thoughts?  I'll make a PR if you agree.

**Comment by cdzombak** [comment]
> I think the right solution for this is to not set blanket 444 permissions, but to only remove write access if write access is set.

This sounds reasonable to me.

**Comment by mglidden** [comment]
Thanks for letting me know – that sounds like the correct solution. 

This functionality has actually been merged into 0.37.0 (https://github.com/CocoaPods/CocoaPods/pull/3438), so this is also an issue with CocoaPods itself.

**Comment by mglidden** [comment]
I've submitted a pull-request to fix this in CocoaPods (https://github.com/CocoaPods/CocoaPods/pull/3514), and I'll update the plugin (and add a deprecation warning) tomorrow.

FYI, the source in the Crashlytics pod does not appear to be official in anyway – it's just some guy hosting it on GitHub. He could theoretically switch out the framework, which would result in shipping that code. We switched Crashlytics back to the manually linked version for these security concerns.

**Comment by brianpartridge** [comment]
Thanks for the fix, and I'm really glad this is in the main tool rather than a plugin. 

You're definitely right about the concerns with the Crashlytics pod, we'll probably end up maintaining our own mirror of it anyway. However the same issue could happen to any pod where a consumer does not audit the changes that went into a new version.
